import { Inter } from 'next/font/google';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: '신정중학교 소셜 홈페이지',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
            <Script src="https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.min.js" crossOrigin="anonymous" />
        </html>
    );
}
